language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - pep8 --ignore=E501 gedcom/
  - python -m unittest gedcom.test_validation_messages gedcom.test_people gedcom.test_families